In [7]:
import numpy as np
import pandas as pd

#### 1) Replace Nan with 0 and Interchange 3 rows and 3 columns of 2D array [[6, -8, 73, -110], [np.nan, -8, 0, 94]] 

In [8]:
array = np.array([[6, -8, 73, -110], [np.nan, -8, 0, 94]] )
print("Array: \n",array)
replace_nan = np.nan_to_num(array,nan = 0)
print("\nAfter replacing nan with zero : \n",replace_nan)
interchange = replace_nan.T
print("\nAfter interchange : \n",interchange)

# it is only a 2 X 4 array so interchange of 3 rows and three columns is not possible but if there is a higher order array is given like 6 X 6 array then we can use slicing like this - 
# sub = arr[:3,:3]
# arr[:3,:3] = sub.T 
# to achieve the interchange of specified rows and columns


Array: 
 [[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]

After replacing nan with zero : 
 [[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

After interchange : 
 [[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


#### 2) Move axes of 3D array to new positions 

In [9]:
arr = np.arange(24).reshape(2, 3, 4)

print("\nOriginal 3D Array Shape:", arr.shape)
print(arr)

moved = np.moveaxis(arr, 0, 2)

print("\nAfter moving axis 0 to axis 2:")
print("New Shape:", moved.shape)
print(moved)
print("\n")
moved = np.moveaxis(arr, 0, 1)

print("\nAfter moving axis 0 to axis 1:")
print("New Shape:", moved.shape)
print(moved)


Original 3D Array Shape: (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

After moving axis 0 to axis 2:
New Shape: (3, 4, 2)
[[[ 0 12]
  [ 1 13]
  [ 2 14]
  [ 3 15]]

 [[ 4 16]
  [ 5 17]
  [ 6 18]
  [ 7 19]]

 [[ 8 20]
  [ 9 21]
  [10 22]
  [11 23]]]



After moving axis 0 to axis 1:
New Shape: (3, 2, 4)
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]


#### 3) Replace NaN values with average of columns 

In [ ]:

arr = np.array([[10, 20, np.nan],
                [30, np.nan, 50],
                [40, 60, 70]])

print("\nOriginal Array with NaN:\n", arr)

col_mean = np.nanmean(arr, axis=0)

print("\nColumn Means:\n", col_mean)

inds = np.where(np.isnan(arr))
print("\n",inds)
arr[inds] = np.take(col_mean, inds[1])

print("\nAfter replacing NaN with column averages:\n", arr)


Original Array with NaN:
 [[10. 20. nan]
 [30. nan 50.]
 [40. 60. 70.]]

Column Means:
 [26.66666667 40.         60.        ]

 (array([0, 1]), array([2, 1]))

After replacing NaN with column averages:
 [[10. 20. 60.]
 [30. 40. 50.]
 [40. 60. 70.]]


#### 4) Replace negative value with zero in numpy array using replace

In [ ]:
arr = np.array([[4, -2, 7],[-5, 9, -1]])

print("\nOriginal Array:\n", arr)

arr[arr < 0] = 0

print("\nAfter replacing negative values with 0:\n", arr)


Original Array:
 [[ 4 -2  7]
 [-5  9 -1]]

After replacing negative values with 0:
 [[4 0 7]
 [0 9 0]]
