In [25]:
import numpy as np


#### 1) Combining a one and a two-dimensional NumPy Array 

In [26]:
arr1 = np.array([1,2])
arr2 = np.array([[3,4],[5,6]])
print(arr1,"\n")
print(arr2,"\n")
arr3 = np.concatenate((arr2,[arr1]),axis = 0)
print(arr3)

[1 2] 

[[3 4]
 [5 6]] 

[[3 4]
 [5 6]
 [1 2]]


#### 2) Flatten a 2d numpy array into 1d array 

In [27]:
arr = np.array([[3,4],[5,6]])
print("Original array:\n",arr)
res = arr.reshape(-1)
print("flattened array:\n",res)

Original array:
 [[3 4]
 [5 6]]
flattened array:
 [3 4 5 6]


#### 3) Reverse a numpy array 

In [28]:
arr = np.array([1,2,3,4,5,6])
print("Original array:\n",arr)
res = arr[::-1]
print("reversed array:\n",res)
# or
print("reversed array:\n",np.flip(arr))

Original array:
 [1 2 3 4 5 6]
reversed array:
 [6 5 4 3 2 1]
reversed array:
 [6 5 4 3 2 1]


#### 4) (i) Practice operations like Get the maximum value from given array Get the minimum value from given array

In [29]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print("Array:")
print(arr)

# Maximum value
print("Maximum =", np.max(arr))

# Minimum value
print("Minimum =", np.min(arr))

# Number of rows and columns
rows, cols = arr.shape
print("Rows =", rows)
print("Columns =", cols)

# Select all elements
print("All Elements:")
for row in arr:
    for element in row:
        print(element, end=" ")
print()

# Specific element
print("Element at row 1, column 2 =", arr[1, 2])

# Sum using for loop
total = 0
for row in arr:
    for element in row:
        total += element

print("Sum =", total)

Array:
[[10 20 30]
 [40 50 60]]
Maximum = 60
Minimum = 10
Rows = 2
Columns = 3
All Elements:
10 20 30 40 50 60 
Element at row 1, column 2 = 60
Sum = 210


#### (ii) Find the number of rows and columns of a given array using NumPy Select the elements from a given array (each element and specific element)

In [30]:
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([2, 4, 5])

print("Addition:")
print(arr1 + arr2)

print("Subtraction:")
print(arr1 - arr2)

print("Multiplication:")
print(arr1 * arr2)

print("Division:")
print(arr1 / arr2)

Addition:
[12 24 35]
Subtraction:
[ 8 16 25]
Multiplication:
[ 20  80 150]
Division:
[5. 5. 6.]


 
#### (iii) Find the sum of values in a 2D array using for loop Adding, Subtracting, multiplying, dividing arrays in Numpy 

In [31]:
import numpy as np

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("3D Array:")
print(arr)

print("\nUsing Nested For Loops:")

for matrix in arr:
    for row in matrix:
        for element in row:
            print(element)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Using Nested For Loops:
1
2
3
4
5
6
7
8



#### 5) Iterate 3D array using for loop and nditer 

In [32]:
import numpy as np

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Using nditer:")

for x in np.nditer(arr):
    print(x)

Using nditer:
1
2
3
4
5
6
7
8


#### 6) Study the following program import numpy as np 
#### create a numpy 1d-arrays arr1 = np.array([3, 4]) arr2 = np.array([1, 0]) 
#### find average of NumPy arrays avg = (arr1 + arr2) / 2 print("Average of NumPy arrays:\n", avg) -> Calculate average mean median mode values of two NumPy 2d-arrays

In [33]:
import numpy as np

arr1 = np.array([[10, 20],
                 [30, 40]])

arr2 = np.array([[5, 15],
                 [25, 35]])

avg = (arr1 + arr2) / 2

print("Average Array:")
print(avg)

Average Array:
[[ 7.5 17.5]
 [27.5 37.5]]


In [34]:
import numpy as np

arr1 = np.array([[10, 20],
                 [30, 40]])

arr2 = np.array([[5, 15],
                 [25, 35]])

combined = np.concatenate((arr1, arr2))

print("Combined Array:")
print(combined)

print("Mean =", np.mean(combined))

Combined Array:
[[10 20]
 [30 40]
 [ 5 15]
 [25 35]]
Mean = 22.5


In [35]:
import numpy as np

arr1 = np.array([[10, 20],
                 [30, 40]])

arr2 = np.array([[5, 15],
                 [25, 35]])

combined = np.concatenate((arr1, arr2))

print("Median =", np.median(combined))

Median = 22.5


In [36]:
import numpy as np

arr1 = np.array([[10, 20],
                 [20, 40]])

arr2 = np.array([[5, 15],
                 [20, 35]])

combined = np.concatenate((arr1, arr2))

flat = combined.flatten()

values, counts = np.unique(flat, return_counts=True)

mode = values[np.argmax(counts)]

print("Mode =", mode)

Mode = 20


In [37]:
import numpy as np
arr1 = np.array([[10, 20],
                 [20, 40]])

arr2 = np.array([[5, 15],
                 [20, 35]])

combined = np.concatenate((arr1, arr2))

print("Mean =", np.mean(combined))
print("Median =", np.median(combined))

flat = combined.flatten()

values, counts = np.unique(flat, return_counts=True)

mode = values[np.argmax(counts)]

print("Mode =", mode)

Mean = 20.625
Median = 20.0
Mode = 20
