## Create numpy array and perform following operation

In [2]:
import numpy as np


#### > Convert 1D array to 2D 

In [4]:
arr = np.array([1,2,3,4,5,6,7,8])
print("original 1D Array:\n",arr)
res = arr.reshape(2,4)
print("coverted into 2D Array:\n",res)

original 1D Array:
 [1 2 3 4 5 6 7 8]
coverted into 2D Array:
 [[1 2 3 4]
 [5 6 7 8]]



#### > Print Array Attributes(Like shape, dimenssion, data type, itemsize)

In [11]:
arr = np.arange(0,30).reshape(5,3,2)
print("array:\n",arr)
print("\nshape:",arr.shape)
print("\nsize:",arr.size)
print("\nitemsize:",arr.itemsize)
print("\ndata type:",arr.dtype)
print("\ndimensions:",arr.ndim)

array:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]

 [[24 25]
  [26 27]
  [28 29]]]

shape: (5, 3, 2)

size: 30

itemsize: 8

data type: int64

dimensions: 3


 
#### > Create a 3×3 NumPy array of all 9 

In [13]:
arr = np.full((3,3),9)
print("Array:\n",arr)

Array:
 [[9 9 9]
 [9 9 9]
 [9 9 9]]



#### > Create a 1D array of 10 evenly spaced values between 25 and 125 

In [14]:
arr = np.linspace(25,125,10)
print("array:\n",arr)

array:
 [ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]



#### > Convert a Python list into a NumPy array 

In [15]:
List = [1,2,3,4,5,6,7,8]
print(List,type(List))
arr = np.array(List)
print(arr,type(arr))


[1, 2, 3, 4, 5, 6, 7, 8] <class 'list'>
[1 2 3 4 5 6 7 8] <class 'numpy.ndarray'>



#### > Reverse a 1D NumPy array 

In [16]:
arr = np.array([1,2,3,4,5,6,7,8])
print("1D array:\n",arr)
res = np.flip(arr)
print("reversed 1D array:\n",res)

1D array:
 [1 2 3 4 5 6 7 8]
reversed 1D array:
 [8 7 6 5 4 3 2 1]



#### > Create a 4×4×3 array and extract value at its second set, first row and last column 

In [18]:
arr = np.arange(0,48).reshape(4,4,3)
print("array:\n",arr)
value = arr[1,0,2]
print("\nExtracted value:",value)

array:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]

Extracted value: 14



#### > Create a 4×4 and Extract Odd Rows and Even Columns 

In [21]:
arr = np.arange(0,16).reshape(4,4)
print("array:\n",arr)
val = arr[0::2,1::2]
print("\nExtracted odd rows and even columns:\n",val)

array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted odd rows and even columns:
 [[ 1  3]
 [ 9 11]]



#### > Slice the first two rows and first two columns of second set from a 4×4×3 array 

In [22]:
arr = np.arange(0,48).reshape(4,4,3)
print("array:\n",arr)
s = arr[1,0:2,0:2]
print("\nsliced first two rows and first two columns of second set of array:\n",s)

array:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]

sliced first two rows and first two columns of second set of array:
 [[12 13]
 [15 16]]



#### > Replace all odd numbers in a NumPy array with -1 by itterating using for loop [[23, 56, 78, 93], [71, 82,13, 24]] 


In [23]:
arr = np.array([[23, 56, 78, 93], [71, 82,13, 24]])
print("array:\n",arr)
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if arr[i, j] % 2 != 0:
            arr[i, j] = -1
print("\narray with replaced odd numbers:\n",arr)            

array:
 [[23 56 78 93]
 [71 82 13 24]]

array with replaced odd numbers:
 [[-1 56 78 -1]
 [-1 82 -1 24]]


#### > Get the indices of non-zero elements in an array [1, 0, 2, 0, 3, 0, 4] 

In [25]:
arr = np.array( [1, 0, 2, 0, 3, 0, 4])
print("array:\n",arr)
indices = np.nonzero(arr)
print("\nindices of non zero elements:\n",indices)

array:
 [1 0 2 0 3 0 4]

indices of non zero elements:
 (array([0, 2, 4, 6]),)



#### > Perform arithmetic operations on two NumPy arrays element-wise 
####   Add two NumPy arrays element by element.
####   Multiply two NumPy arrays element by element. 

In [26]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
print("Array 1:\n",arr1)
print("\nArray 2:\n",arr2)
print("\nAddition:\n",arr1 + arr2)
print("\nMultiplication:\n",arr1 * arr2)

Array 1:
 [[1 2 3]
 [4 5 6]]

Array 2:
 [[ 7  8  9]
 [10 11 12]]

Addition:
 [[ 8 10 12]
 [14 16 18]]

Multiplication:
 [[ 7 16 27]
 [40 55 72]]


#### > Write a code to compute the dot product of two NumPy arrays arr1 = [15, 20, 25] ,arr2 = [10,40,37].

In [27]:
a = np.array([15,20,25])
b = np.array([10,40,37])
print("\nArray 1:\n",a)
print("\nArray 2:\n",b)
print("\nDot product:\n",a.dot(b))


Array 1:
 [15 20 25]

Array 2:
 [10 40 37]

Dot product:
 1875
